name: AxVaults
version: '${project.version}'
main: com.artillexstudios.axvaults.AxVaults
api-version: '1.18'
folia-supported: true

softdepend:
  - PlaceholderAPI

libraries:
  - org.mariadb.jdbc:mariadb-java-client:3.1.4

permissions:
  axvaults.vault.1:
    default: true
  axvaults.selector:
    default: true
  axvaults.admin:
    default: op
  axvaults.openremote:
    default: true
  axvaults.itempicker:
    default: true